version: '3'
services:

  mongo:
    image: mongo
    container_name: jguwekamongo
    restart: always

  jguweka:
    image: jguweka/jguweka:OAS3
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.50'
    links:
      - "mongo:mongodb"
    expose:
      - "8080"
    depends_on:
      - mongo
    labels:
      - "service-name:jguweka"
      - "service-type:app-srv"
      - "environment:test"

  loadbalancer:
    image: nginx:latest
    container_name: loadbalancer
    restart: always
    volumes:
      - ./loadbalancer/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - jguweka
    ports:
      - "80:80"
    depends_on:
    - jguweka
